export const profilesData = [
  [
    {
      name: 'Tolulope Aina',
      username: '@toluene',
      backgroundImg: 'dashboard-img.svg',
      picture: 'user1.svg',
      track: 'UI/UX Design Intern',
      level: 'Master Class',
      address: 'Lagos, Center of Excellence, Nigeria',
      email: 'toluene@gmail.com',
      phone: '+23456797900429',
      occupation: 'Student',
      company: 'Stutern',
    },
    {
      name: 'Blessing Dan',
      username: '@blessed',
      backgroundImg: 'dashboard-img.svg',
      picture: 'user2.svg',
      track: 'Backend Intern',
      level: 'Beginner Class',
      address: 'Abuja, Federal Capital Territory, Nigeria',
      email: 'blessing@gmail.com',
      phone: '+23456797900429',
      occupation: 'unemployed',
      company: 'Nill',
    },
    {
      name: 'Hauwa Azeez',
      username: '@ennyola',
      backgroundImg: 'dashboard-img.svg',
      picture: 'user3.svg',
      track: 'Frontend Intern',
      level: 'Master Class',
      address: 'Anambra, Home for All, Nigeria',
      email: 'hauwa@gmail.com',
      phone: '+23456797900429',
      occupation: 'cashier',
      company: 'Wema Bank',
    },
    {
      name: 'Tobi Imohi',
      username: '@oluwatobiloba',
      backgroundImg: 'dashboard-img.svg',
      picture: 'user4.svg',
      track: 'UI/UX Design Intern',
      level: 'Beginner Class',
      address: 'Lagos, Center of Excellence, Nigeria',
      email: 'tobi@gmail.com',
      phone: '+23456797900429',
      occupation: 'Store Keeper',
      company: 'Go foods',
    },
    {
      name: 'Emma Ogbuagu',
      username: '@emmanuel',
      backgroundImg: 'dashboard-img.svg',
      picture: 'user5.svg',
      track: 'Backend Intern',
      level: 'Intermediate Class',
      address: 'Abuja, Federal Capital Territory, Nigeria',
      email: 'emmanuel@gmail.com',
      phone: '+23456797900429',
      occupation: 'Sales Rep',
      company: 'INTELTD',
    },
    {
      name: 'David Femi',
      username: '@dave',
      backgroundImg: 'dashboard-img.svg',
      picture: 'user6.svg',
      track: 'Frontend Intern',
      level: 'Beginner Class',
      address: 'Lagos, Center of Excellence, Nigeria',
      email: 'dave@gmail.com',
      phone: '+23456467900429',
      occupation: 'Student',
      company: 'Stutern',
    },
    {
      name: 'Hadiza Abdulazeez',
      username: '@haddy',
      backgroundImg: 'dashboard-img.svg',
      picture: 'user7.svg',
      track: 'UI/UX Design Intern',
      level: 'Intermediate Class',
      address: 'Abuja, Federal Capital Territory, Nigeria',
      email: 'Hadizaabdulaziz@gmail.com',
      phone: '+23456797900767',
      occupation: 'Accountant',
      company: 'AEDC',
    },
  ],
  [
    {
      name: 'Adubi Rotimi',
      username: '@rotimi',
      backgroundImg: 'dashboard-img.svg',
      picture: 'tutor1.svg',
      track: 'Design Tutor',
      level: 'All Class',
      address: 'Anambra, Home for All, Nigeria',
      email: 'rotimi@gmail.com',
      phone: '+23456797900975',
      occupation: 'UI/UX Designer',
      company: 'Microsoft',
    },
    {
      name: 'Tayo Akinn',
      username: '@tayo',
      backgroundImg: 'dashboard-img.svg',
      picture: 'tutor2.svg',
      track: 'Backend Tutor',
      level: 'All Class',
      address: 'Lagos, Center of Excellence, Nigeria',
      email: 'tayo@gmail.com',
      phone: '+23456797900534',
      occupation: 'Backend Developer',
      company: 'Facebook',
    },
    {
      name: 'Taiwo Dauda',
      username: '@toluene',
      backgroundImg: 'dashboard-img.svg',
      picture: 'tutor3.svg',
      track: 'Design Tutor',
      level: 'All Class',
      address: 'Abuja, Federal Capital Territory, Nigeria',
      email: 'taiwo@gmail.com',
      phone: '+23456797900534',
      occupation: 'UI/UX Designer',
      company: 'Amazon',
    },
    {
      name: 'Jelili Umaru',
      username: '@jelili',
      backgroundImg: 'dashboard-img.svg',
      picture: 'tutor4.svg',
      track: 'Frontend Tutor',
      level: 'All Class',
      address: 'Lagos, Center of Excellence, Nigeria',
      email: 'jelili@gmail.com',
      phone: '+23456797900534',
      occupation: 'Web Developer',
      company: 'Turing',
    },
  ],
];
