import ModuleOne from '../../../../../assets/moduleone.png';
import ModuleTwo from '../../../../../assets/module-two.png';
import ModuleThree from '../../../../../assets/module-three.png';
import ModuleFour from '../../../../../assets/module-four.png';
import ModuleFive from '../../../../../assets/module-five.png';
import ModuleSix from '../../../../../assets/module-six.png';
import ModuleSeven from '../../../../../assets/module-seven.png';
import ModuleEight from '../../../../../assets/module-eight.png'

const courseData = [
  {
    id: '1',
    categoryId: 'beginner',
    img: ModuleOne,
    header: 'Module 1',
    text: 'Introduction to Product Design Beginner',
    link: '/user/moduleone',
    name: 'Module 1: Assignment 1',
    date: 'Due Date: 25th Dec 2022',
    time: 'Today , 7:19am',
    finalGrade: '180/200',
    grade: '99%',
  },
  {
    id: '1',
    categoryId: 'beginner',
    img: ModuleTwo,
    header: 'Module 2',
    text: 'Tools of the Trade Beginner',
    link: '/moduletwo',
    name: 'Module 1: Assignment 1',
    date: 'Due Date: 25th Dec 2022',
    grade: '99%',
    time: 'Today , 7:19am',
    finalGrade: '180/200',
  },
  {
    id: '1',
    categoryId: 'beginner',
    img: ModuleThree,
    header: 'Module 3',
    text: 'Basic UI Elements Beginner',
    link: '/modulethree',
    name: 'Module 1: Assignment 1',
    date: 'Due Date: 25th Dec 2022',
    grade: '99%',
    time: 'Today , 7:19am',
    finalGrade: '180/200',
  },
  {
    id: '1',
    categoryId: 'beginner',
    img: ModuleFour,
    header: 'Module 4',
    text: 'Principles of Design Beginner',
    link: '/modulefour',
    name: 'Module 1: Assignment 1',
    date: 'Due Date: 25th Dec 2022',
    grade: '99%',
    time: 'Today , 7:19am',
    finalGrade: '180/200',
  },
  {
    id: '1',
    categoryId: 'beginner',
    img: ModuleFive,
    header: 'Module 5',
    text: 'Design Thinking Process Beginner',
    link: '/modulefive',
    name: 'Module 1: Assignment 1',
    date: 'Due Date: 25th Dec 2022',
    grade: '99%',
    time: 'Today , 7:19am',
    finalGrade: '180/200',
  },
  {
    id: '1',
    categoryId: 'beginner',
    img: ModuleSix,
    header: 'Module 6',
    text: 'Prototyping',
    link: '/modulesix',
    name: 'Module 1: Assignment 1',
    date: 'Due Date: 25th Dec 2022',
    grade: '99%',
    time: 'Today , 7:19am',
    finalGrade: '180/200',
  },
  {
    id: '1',
    categoryId: 'beginner',
    img: ModuleSeven,
    header: 'Module 7',
    text: 'Finding and using design inspiration',
    link: '/moduleseven',
    name: 'Module 1: Assignment 1',
    date: 'Due Date: 25th Dec 2022',
    grade: '99%',
    time: 'Today , 7:19am',
    finalGrade: '180/200',
  },
  {
    id: '1',
    categoryId: 'beginner',
    img: ModuleEight,
    header: 'Module 8',
    text: 'Final Project',
    link: '/moduleight',
    name: 'Module 1: Assignment 1',
    date: 'Due Date: 25th Dec 2022',
    grade: '99%',
    time: 'Today , 7:19am',
    finalGrade: '180/200',
  },
  {
    id: '1',
    categoryId: 'intermediate',
    img: ModuleOne,
    header: 'Module 1',
    text: 'Introduction to Product Design intermediate',
    link: '/moduleone',
    name: 'Module 1: Assignment 1',
    date: 'Due Date: 25th Dec 2022',
    grade: '99%',
    time: 'Today , 7:19am',
    finalGrade: '180/200',
  },
  {
    id: '1',
    categoryId: 'intermediate',
    img: ModuleTwo,
    header: 'Module 2',
    text: 'Tools of the Trade intermediate',
    link: '/moduletwo',
    name: 'Module 1: Assignment 1',
    date: 'Due Date: 25th Dec 2022',
    grade: '99%',
    time: 'Today , 7:19am',
    finalGrade: '180/200',
  },
  {
    id: '1',
    categoryId: 'intermediate',
    img: ModuleThree,
    header: 'Module 3',
    text: 'Basic UI Elements intermediate',
    link: '/modulethree',
    name: 'Module 1: Assignment 1',
    date: 'Due Date: 25th Dec 2022',
    grade: '99%',
    time: 'Today , 7:19am',
    finalGrade: '180/200',
  },
  {
    id: '1',
    categoryId: 'intermediate',
    img: ModuleFour,
    header: 'Module 4',
    text: 'Principles of Design intermediate',
    link: '/modulefour',
    name: 'Module 1: Assignment 1',
    date: 'Due Date: 25th Dec 2022',
    grade: '99%',
    time: 'Today , 7:19am',
    finalGrade: '180/200',
  },
  {
    id: '1',
    categoryId: 'intermediate',
    img: ModuleFive,
    header: 'Module 5',
    text: 'Design Thinking Process intermediate',
    link: '/modulefive',
    name: 'Module 1: Assignment 1',
    date: 'Due Date: 25th Dec 2022',
    grade: '99%',
    time: 'Today , 7:19am',
    finalGrade: '180/200',
  },
  {
    id: '1',
    categoryId: 'intermediate',
    img: ModuleSix,
    header: 'Module 6',
    text: 'Prototyping intermediate',
    link: '/modulesix',
    name: 'Module 1: Assignment 1',
    date: 'Due Date: 25th Dec 2022',
    grade: '99%',
    time: 'Today , 7:19am',
    finalGrade: '180/200',
  },
  {
    id: '1',
    categoryId: 'intermediate',
    img: ModuleSeven,
    header: 'Module 7',
    text: 'Finding and using design inspiration intermediate',
    link: '/moduleseven',
    name: 'Module 1: Assignment 1',
    date: 'Due Date: 25th Dec 2022',
    grade: '99%',
    time: 'Today , 7:19am',
    finalGrade: '180/200',
  },
  {
    id: '1',
    categoryId: 'intermediate',
    img: ModuleEight,
    header: 'Module 8',
    text: 'Final Project intermediate',
    link: '/moduleight',
    name: 'Module 1: Assignment 1',
    date: 'Due Date: 25th Dec 2022',
    grade: '99%',
    time: 'Today , 7:19am',
    finalGrade: '180/200',
  },
];

export default courseData;
